### ISSUE TITLE
Add missing design for last step and mobile view

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/dash-faucet#2]
# Issue

There is last step missing from the initial design, and also missing some small improvements, like social icons, notifications and mobile view.

* Build an design for notifications based on react-toastify
* Add icons for different socials
* Add last step action, when transaction was sent
* Add mobile design

**Comment by blackmirrordesigner** [comment]
<img width="534" alt="image" src="https://github.com/user-attachments/assets/c3d16282-c1cf-496b-bf63-dc7ce1a3657e">
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/62005368-b68f-4180-a5c8-8e5e8022cbde">

1. Modals notifications https://www.figma.com/design/CaUFStntSECJlI7AYSvL2N/Notifications?node-id=0-1&t=ioDfPnBnmaLR13c4-1

<img width="755" alt="image" src="https://github.com/user-attachments/assets/ada2ee8a-d1ab-4fe8-a5f4-6311aa3e0490">
<img width="762" alt="image" src="https://github.com/user-attachments/assets/2e76568a-548c-4a44-ad7d-cd90c3c388cc">

<img width="780" alt="image" src="https://github.com/user-attachments/assets/fb6e11f8-cbe2-4060-9b35-6daca58f6f9b">

2. Social icons: https://www.figma.com/design/5S5bpGyJPfdrYIuC5TK98C/Social-Icons?node-id=0-1&t=y35E4Gk7Zj2lQBQw-1

<img width="991" alt="image" src="https://github.com/user-attachments/assets/e5e13fe6-30e7-4be6-b026-c0bea9fba444">

3. Last step design, when transaction was sent https://www.figma.com/design/olVWRnctwW1nsGy7oVAquf/Last-step?node-id=0-1&t=RwYBLQVTcd4xQ2c1-1

<img width="421" alt="image" src="https://github.com/user-attachments/assets/76bedee0-fafc-4415-9854-4d48c80ca4e8">

4. Responsive mobile design https://www.figma.com/design/oRQ7JP1VbiQlrPfRFNZ0aC/Responsive?node-id=0-1&t=FCgQzZMQZnffk1gY-1
